nunomaduro/termwind

README.md
Found out this typo on the readme while testing.
=> bgColor method does not exist anymore is now bg

src/Components/Element.php, tests/Line.php
This PR adds the capability to add a `px` and `mx` method to the line element, inspired by https://tailwindcss.com/docs/padding#add-horizontal-padding
This will replace the need to have `$line->pl($padding)->pr($padding)` and use only the `$this->px($padding)` the same logic is added also the `$line->ml()` and `$line->mr()`.
=> Add Horizontal Margin and Padding

src/Utils/Color.php
Hey @nunomaduro!
This package is looking really cool! 😄
This PR's only a small one. It just adds a new `Color` class that exposes all of the default Tailwind colours for using in the `textColor` and `bg` methods. For example, you could do something like this:
```php
use Termwind\Utils\Color;
line('Hello')->textColor(Color::WHITE)->bg(Color::BLUE_300)->render();
```
I think this could be pretty useful because it could give devs a good starting point to work from, with colours that they're probably used to using from Tailwind.
Hopefully, this is something that you think would be worthwhile.
As a side note, I got the colours list from here: https://github.com/tailwindlabs/tailwindcss/blob/master/src/public/colors.js
=> Added colours utility class

README.md, src/Components/Element.php, tests/Element.php, tests/Span.php, tests/Termwind.php
To have it working the same way `text-color` and `bg-color` and with the addition of accepting strings make sense to remove `ml1`, `ml2`, etc. and have the `margin` and `padding` working the same way.
What do you think @nunomaduro?
=> Remove padding and margin proxy methods

src/Components/Element.php, tests/Span.php
After checking the TailwindCSS documentation, https://tailwindcss.com/docs/text-transform#capitalize
Makes sense to rename titlecase to capitalize to match the same method name.
=> Rename `titlecase` to `capitalize` in order to match the tailwindcss method name.

README.md, src/Components/Anchor.php, src/Components/Element.php, src/Functions.php, src/Termwind.php, tests/Anchor.php
This PR adds an `Anchor` component and an `a()` function to render clickable hyperlinks.
```php
// Adds a hyperlink
a('https://github.com/nunomaduro/termwind');
// Adds a hyperlink with text value
a('Termwind')->href('https://github.com/nunomaduro/termwind');
```
=> Implement anchor element

src/Components/Element.php, tests/Span.php
This PR adds a method available on TailwindCSS `line-through`: https://tailwindcss.com/docs/text-decoration#line-through.
@nunomaduro checked for an option on the symfony/console package but did not found any.
Let me know if there is a better option.
=> Add text decoration line-through method

README.md
Correct me if I'm wrong, but I think this was an unintentional change when you converted `line()` to `span()`.
=> chore: fix incorrect span find & replace

src/Termwind.php, src/ValueObjects/Node.php, tests/classes.php, tests/div.php, tests/dl.php, tests/node.php, tests/ol.php, tests/render.php, tests/span.php, tests/ul.php
```html
<div>
<span class="px-1">hello</span>
<span class="px-1">world</span>
</div>
```
Will render
```html
&nbsp;hello&nbsp;&nbsp;world&nbsp;
```
--------
```html
<div>
<span class="px-1">hello</span> <span class="px-1">world</span>
</div>
```
Will render
```html
&nbsp;hello&nbsp;&nbsp;&nbsp;world&nbsp;
```
fixed #94
=> fix: Fixes problem with empty spaces between two elements

src/Html/PreRenderer.php, src/HtmlRenderer.php, tests/pre.php
We can try to add styles for every line inside pre element
```html
<pre class="bg-blue text-red font-bold">
<h1>Introduction</h1>
<div>The body of your message.</div>
Thanks,
Laravel
© 2021 Laravel. All rights reserved.
</pre>
```
There is a problem with line width. If I didn't pay attention to the line width, I got something like this
Then I decided to get width for the longest line in a html and apply `str_pad` function to every line. 
fixed #91
=> feat: Adds ability to use styles for pre element

README.md
This PR adds to the `README.md` the docs about the HTML elements supported.
@nunomaduro can you take a look on this and check if is a good approach for the documentation?
Thanks.
=> docs: Add HTML Elements Supported to the documentation.

src/HtmlRenderer.php, tests/render.php
This PR fixes the issue #90.
No longer converts a string to a `<p>` tag.
=> fix: Fixes the string content to not be a `<p>` tag

src/Components/Element.php, src/Enums/Color.php, src/Exceptions/InvalidColor.php, src/ValueObjects/Style.php, tests/colors.php
This PR adds the capability to overwrite existent colors or create new colors.
```php
use function Termwind\{render, setColors};
setColors([
'blue-300' => '#0133dc',
'badass' => '#bada55',
]);
<div class="my-1">
<div class="bg-blue-300">
Termwind now supports <b>`setColors()`</b>
</div>
<div class="mt-1 bg-badass text-black">
Can be used like this: <b>`setColors(['badass' => '#bada55'])`</b>
</div>
</div>
HTML);
```
=> feat: Add `setColors` 

src/ValueObjects/Styles.php, tests/render.php
This PR fixes an issue that I found while testing:
```php
<div class="bg-red-700 p-5">
<div><b>Termwind</b> now supports `w-full`</div>
</div>
```
=> Should always inherit all parent styles

src/ValueObjects/Styles.php, tests/render.php
This PR allows the inheritance for `margin` and `padding`.
```php
<div class="px-5 bg-green-600">
<div class="mx-10 bg-blue-800">
<span class="mx-5">
<span class="w-1/2 mr-1 bg-rose-500 px-2">A</span>
<span class="w-1/2 ml-1 bg-rose-600 px-2 text-right">B</span>
</span>
</div>
</div>
HTML);
```
=> feat: Allows the inheritance for `margin` and `padding`

README.md, src/Terminal.php, src/Termwind.php, tests/terminal.php
This PR adds a function to allow the terminal to be cleared.
```php
use function Termwind\{render, terminal};
terminal()->clear();
<div class="my-2 mx-2 w-full bg-green-500 font-bold text-black text-center">
Now there is a capability to clear the "messy" terminal screen
</div>
HTML);
```
=> feat: Add `terminal()->clear()` method.

README.md, composer.json, playground.php, src/Functions.php, src/Helpers/QuestionHelper.php, src/Question.php, tests/Pest.php, tests/ask.php
This PR adds the capability to prompt the user with a question and style it.
```php 
use function Termwind\{ask, render};
$answer = ask(<<<HTML
<span class="mt-1 ml-2 mr-1 bg-green px-1 text-black">What is your name?</span>
HTML);
render("
<span class='my-1 mx-2'>
The answer was: <b class='px-1 bg-green text-black'>$answer</b>
</span>
");
```
> It does fallback to Pest v1.0 because of the need of the `pest-plugin-mock`.
=> feat: Adds `ask()` method.

README.md, src/ValueObjects/Styles.php, tests/classes.php
This PR adds the capability of limiting the width of an element.
```php
render(<<<HTML
<div class="w-full max-w-20 bg-red"></div>
HTML);
```
=> feat: Add `max-w-{width}` class.

README.md, playground.php, src/ValueObjects/Styles.php, tests/classes.php, tests/render.php, tests/style.php
This PR adds the support for `padding-top` and `padding-bottom` classes.
```php
<div class="my-1 mx-2">
<div class="text-white bg-green-800 px-4 py-1">
Termwind now supports <b>`py`</b>
</div>
</div>
HTML);
```
=> feat: Add support for `py`, `pt` and `pb`.

README.md, playground.php, src/ValueObjects/Styles.php, tests/classes.php
Hey,
This PR adds the support to the `space-y` and `space-x` utility class from tailwind: https://tailwindcss.com/docs/space
```php
<div class="my-1 mx-2 space-y-1">
<div class="font-bold uppercase">Title</div>
<div>Lorem ipsum dolor sit amet, consectetur adipisicing elit</div>
<div class="text-gray">© 2022</div>
</div>
HTML);
```
instead of:
```php
<div class="my-1 mx-2">
<div class="font-bold uppercase">Title</div>
<div class="mt-1">Lorem ipsum dolor sit amet, consectetur adipisicing elit</div>
<div class="mt-1 text-gray">© 2022</div>
</div>
HTML);
```
=> feat: Add support for `space-y` and `space-x`

README.md, playground.php, src/Actions/StyleToMethod.php, tests/mediaQueries.php
This PR adds the support for `MediaQueries`.
```php
<div class="mx-2 my-1 space-y-1">
<div>
<span class="bg-green-500 text-black font-bold px-1">Media Queries with <b>Termwind</b>?</span>
<em class="ml-2">Sure, why not?</em>
</div>
<div class="px-1 font-bold bg-blue-500 sm:bg-red-600">
If bg is blue is small, if red > than small
</div>
</div>
HTML);
```
=> feat: Add `MediaQuery` Support.

README.md, playground.php, src/Html/InheritStyles.php, src/ValueObjects/Styles.php, tests/classes.php
This PR adds the `justify-around` and `justify-evenly` to the classes.
=> Feet: Add `justify-around` and `justify-evenly` classes

README.md, src/Components/Element.php, src/Html/InheritStyles.php, src/ValueObjects/Styles.php, tests/classes.php
This PR adds the capability to have a class `flex-1` that will make the element grow and shrink as needed, ignoring the initial size.
The `flex` class works the same way  of the `block`, but will allow a direct child with the `flex-1` class to work.
```php
<div class="flex mx-2 my-1">
<span>First</span>
<span class="flex-1"></span>
<span>Last</span>
</div>
HTML);
```
Will be useful for stuff like this:
Thanks.
=> feat: Add `flex` and `flex-1` classes.

README.md, playground.php, src/Actions/StyleToMethod.php, src/ValueObjects/Styles.php, tests/classes.php
This PR adds the capability to have a way to do a pattern repeat like this:
This is the first class not available on `TailwindCSS`, but is really helpful for CLI outputs.
=> Add `.content-repeat` class

playground.php, src/ValueObjects/Styles.php, tests/classes.php
This PR adds the capability to use the `truncate` class to be used without params.
If it's used without params, it will look for the `width` on the elem.
```php
<div class="mx-2 my-1">
<div class="flex space-x-1">
<span class="flex-1 truncate">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sunt illo et nisi omnis porro at, mollitia harum quas esse, aperiam dolorem ab recusandae fugiat nesciunt doloribus rem eaque nostrum itaque.</span>
<span class="text-green">DONE</span>
</div>
</div>
HTML);
```
=> feat: Allow `truncate` to be used without params.

README.md, src/Html/InheritStyles.php, src/ValueObjects/Styles.php, tests/classes.php
This PR adds support for the `min-w-{width}` class.
With this addition it will possible to make stuff like this:
```php
render(<<<HTML
<div class="flex my-1 mx-2 space-x-1">
<span class="px-1 bg-gray">
min-w
</span>
<span class="flex-1 content-repeat-[.] text-gray min-w-3"></span>
<span>
With the `min-w` addition you can make sure that the content repeat always repeat even if there is no space on the line.
</span>
</div>
HTML);
```
=> feat: Add `min-w-{width}` class.

README.md, src/ValueObjects/Styles.php, tests/classes.php, tests/mediaQueries.php
This PR add the `w-auto` class, that just resets the `width` of the element, it is useful when you use the Media Queries.
```php
<div class="my-1 mx-2 w-25 sm:w-auto truncate px-1 bg-red text-black">
When its a sm screen it will have the width set, but with larger sizes it will have no limitation
</div>
HTML);
```
=> feat: Add support for `w-auto`.

src/Enums/Color.php
If you use try to use a color that doesn't exist, Termwind throws `ColorNotFound`:
```php
render('<div class="text-fakecolor">Hello World</div>')
/* PHP Fatal error:  Uncaught Termwind\Exceptions\ColorNotFound: FAKECOLOR */
```
However orange is available as a color in Termwind, even though it's not [supported by Symfony](https://symfony.com/doc/current/console/coloring.html#using-color-styles). This causes a different error:
```php
render('<div class="text-orange">Hello World</div>');
/* PHP Fatal error: Uncaught Symfony\Component\Console\Exception\InvalidArgumentException:
*     Invalid "orange" color; expected one of (black, red, green, yellow, blue, magenta, cyan,
*     white, default, gray, bright-red, bright-green, bright-yellow, bright-blue, bright-magenta,
*     bright-cyan, …
```
=> Remove 'orange' color

src/Enums/Color.php, src/ValueObjects/Styles.php, tests/classes.php
PR for #141. Allows Termwind to output all 16 standard ANSI colors, so the colors output can match the user's configured terminal theme.
[Symfony Docs](https://symfony.com/doc/current/console/coloring.html#using-color-styles)
FYI: I went with the class name format `text-brightwhite` since dashes aren't currently supported in color names (e.g. `text-bright-white`).
=> Add full ANSI color support

src/ValueObjects/Styles.php, tests/classes.php
This PR fixes a bug when using `truncate` class that was not working when having paddings.
```php
render(<<<HTML
<span class="truncate w-5 px-1">text</span>
HTML);
```
=> Fixes bug when using `truncate` with paddings

src/ValueObjects/Styles.php, tests/classes.php
This PR adds a bug fix when using truncate with `w-full` or `w-1/2`.
```php
render(<<<HTML
<div class="mx-2 my-1">
<div class="w-full truncate">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sunt illo et nisi omnis porro at, mollitia harum quas esse, aperiam dolorem ab recusandae fugiat nesciunt doloribus rem eaque nostrum itaque.</div>
</div>
HTML);
```
=> fix: Truncate to work well with `w-full` or `w-division`.

src/Helpers/QuestionHelper.php, src/Question.php
This PR adds the capability to use `SymfonyStyle` ask method if exists, instead of using the `QuestionHelper` method directly.
This way it for assertions on `Laravel` it will work for `expectQuestion` just like the `$this->ask` method.
=> feat: Allow to use `SymfonyStyle` ask method if exists.

.gitignore, CONTRIBUTING.md, Makefile, docker-compose.yml, docker/Dockerfile
I usually work with **Docker** for all my local applications.
I'm adding a **Docker configuration** alongside a **Makefile** to make it easier for people to contribute.
They don't need to have anything installed on their local machine besides **Docker** to be able to contribute.
=> Add Docker configuration for local setup

src/Html/InheritStyles.php, tests/classes.php
This PR fixes a bug found by @dansysanalyst.
When a `justify-between`, `justify-around`, `justify-evenly` was used with only one child.
It gave the following error:
This PR fixes it.
=> fix: `justify-*` utilities with only one child.
